# Generated by Django 2.1.7 on 2019-07-19 00:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190328_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_items', wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())]))])),
            ],
        ),
    ]
